### PR TITLE
Add Ability to Parse YAML files

### PR DESCRIPTION
**Pull request by tvjust**
Added a check and ability to load YAML files as an alternative to using JSON definition files. The [test.json](https://github.com/redcanaryco/cb-response-surveyor/blob/dd05033121f5dd3474f44bb68a3790444caf3781/definitions/test.yaml) file should be deleted as it was a file created to test certain circumstances that show it works as expected.

### CODE REVIEW

**Comment by brianebeyer** [comment]
image

🔥 🔥 🔥 

If it helps, the best way I've found to handle multiformat config files without depending on sketchy extensions is a chain of attempts, like:

```
contents = fh.read()
parsed = {}
try:
  parsed = json.loads(contents)
except:
  try:
    parsed = yaml.safe_load(contents)
  except:
    log("Unable to load config file as either JSON or YAML")
    sys.exit(1)
```

**Comment by karter99** [comment]
@tvjust i fixed the code for this, but i dont have permissions. :( This should go at line 206 just setting the file_type variable.

```
programs = {}

      with open(definition_file, 'r') as fh:
        contents = fh.read()
        try:
          programs = json.loads(contents)
        except:
          try:
            programs = yaml.safe_load(contents)
          except:
            log("Unable to load config file as either JSON or YAML")
            sys.exit(1)
```

**Comment by tvjust** [comment]
Updated the logic and looks to work as expected with the test file... Thanks for the suggestions @brianebeyer & @karter99  💥 💥 💥

**Comment by rc-abodkins** [comment]
Due to refactoring of code we have created an issue to track this request - https://github.com/redcanaryco/cb-response-surveyor/issues/35

**Pull request closed without merging**
