### PR TITLE
New definition files

### PR DESCRIPTION
**Pull request by MHaggis**
Adding multiple definition files for:
Anonymizers
bittorrent
cracks_keygens
critical_processes
bitcoin miners
proxies, intercepts
screensaver bypass
sysinternals suite

### CODE REVIEW

**Comment by redcanary-it** [comment]
In general, do we want to get into the business of maintaining past and
future hashes for some of these items? I believe that I understand why
they're present, but given that these are survey definitions as opposed to
detection criteria, I think that we may be signing up for unnecessary
maintenance.

**Comment by redcanary-it** [comment]
It occurred to me that you might not get emails from Github when I reply to
these. I've no idea how that works.

Anyway, see below :)

**Comment by MHaggis** [comment]
Correct. Makes sense to start now without MD5's before we get too deep and unable to manage. 
Removed MD5's.

**Comment by MHaggis** [comment]
Two new definition files added:
Network sniffers
Network scanners

**Comment by keithmccammon** [comment]
This is a test comment. Ignore.

**Pull request merged**
